### PR TITLE
Update code samples

### PR DESCRIPTION
**Pull request by mdumandag**
Code samples are updated according to the latest client configuration
changes.

### CODE REVIEW

**Comment by mdumandag** [comment]
I see that in the Node.js code sample, we enable statistics and set the statistics collection period to 1 second. Should we also do it here?

Also, the Node.js code sample sets the `hazelcast.client.cloud.url` to `YOUR_DISCOVERY_URL`. Is that necessary?

**Comment by yunussandikci** [comment]
@mdumandag 
- We encourage to enable statistics to show client statistics from our Hazelast Cloud Panel
- `hazelcast.client.cloud.url` is necessary because we are using different discovery URLs for our development environments.

Thanks

**Comment by mdumandag** [comment]
@yunussandikci  `hazelcast.client.cloud.url` is used only for internal testing, right? I have removed that configuration option after this conversation https://hazelcast.slack.com/archives/CBNUZJKFF/p1606822076062900

You can still change via monkey patching

```python
from hazelcast.discovery import HazelcastCloudDiscovery
HazelcastCloudDiscovery._CLOUD_URL_BASE = "another-coordinator.hazelcast.cloud"
```

But, users shouldn't be dealing with that. Let me enable statistics in the code samples

**Comment by mdumandag** [comment]
https://user-images.githubusercontent.com/29387993/104467899-e2fcc000-55c7-11eb-9a76-252cf6eecd2d.mp4

After I enable statistics, sometimes it is shown, sometimes it is not. Strangely, sometimes after I click on the client name, the popup disappears on its own, and the client's entry disappears along with it. Is that a known problem, or is something wrong with the statistics sent by the Python client? Maybe the format of some fields is not expected? 

Also, another question is that, to gather some statistics(like heap size, cpu usage etc.) we need to install a library along with the hazelcast-python-client. You can install it automatically with the following requirements.txt file 
```text
hazelcast-python-client[stats]~=4.0.0
```
Do we want this for basic code samples like this or basic stats like client name etc. are enough for this? https://hazelcast.readthedocs.io/en/stable/using_python_client_with_hazelcast_imdg.html#enabling-client-statistics See this for details

**Review by yunussandikci — APPROVED** [review]

**Comment by yunussandikci** [comment]
@huseyinbabal Could you please review/merge this and create 4.0 and 4.1 branches from the master branch?

**Review by huseyinbabal — APPROVED** [review]

**Pull request merged**
